name: Arduino CLI build

on:
  pull_request:
    paths:
      - ".github/workflows/build_arduino.yml"
      - "examples/**"
      - "!examples/Usage/pingpair_maple/**"
      - "!examples/rf24_ATTiny/timingSearch3pin/**"

  push:
    paths:
      - ".github/workflows/build_arduino.yml"
      - "examples/**"
      - "!examples/Usage/pingpair_maple/**"
      - "!examples/rf24_ATTiny/timingSearch3pin/**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        fqbn:
          - "arduino:avr:yun"
          - "arduino:avr:uno"
          - "arduino:avr:diecimila"
          - "arduino:avr:nano"
          - "arduino:avr:mega"
          - "arduino:avr:megaADK"
          - "arduino:avr:leonardo"
          - "arduino:avr:micro"
          - "arduino:avr:esplora"
          - "arduino:avr:mini"
          - "arduino:avr:ethernet"
          - "arduino:avr:fio"
          - "arduino:avr:bt"
          # - "arduino:avr:LilyPad"  # board not found
          - "arduino:avr:LilyPadUSB"
          - "arduino:avr:pro"
          - "arduino:avr:atmegang"
          - "arduino:avr:robotControl"
          - "arduino:avr:robotMotor"
          # - "arduino:avr:gemma"  # does not support SPI
          - "arduino:avr:circuitplay32u4cat"
          - "arduino:avr:yunmini"
          - "arduino:avr:chiwawa"
          - "arduino:avr:one"
          - "arduino:avr:unowifi"
          - "arduino:mbed:nano33ble"
          - "arduino:samd:mkr1000"
          - "arduino:samd:mkrzero"
          - "arduino:samd:mkrwifi1010"
          - "arduino:samd:nano_33_iot"
          - "arduino:samd:mkrfox1200"
          - "arduino:samd:mkrwan1300"
          - "arduino:samd:mkrwan1310"
          - "arduino:samd:mkrgsm1400"
          - "arduino:samd:mkrnb1500"
          - "arduino:samd:mkrvidor4000"
          - "arduino:samd:adafruit_circuitplayground_m0"
          - "arduino:samd:mzero_pro_bl"
          - "arduino:samd:mzero_bl"
          - "arduino:samd:tian"
          - "arduino:megaavr:uno2018"
          # - "arduino:megaavr:nano4809"  # board not found

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile examples
        uses: arduino/compile-sketches@main
        with:
          sketch-paths: |
            - examples/GettingStarted
            - examples/GettingStarted_CallResponse
            - examples/AcknowledgementPayloads
            - examples/StreamingData
            - examples/InterruptConfigure
            - examples/MulticeiverDemo
            - examples/FakeBLE
          #   - examples_backup/GettingStarted_HandlingData
          #   - examples_backup/GettingStarted_HandlingFailures
          #   - examples_backup/pingpair_ack
          #   - examples_backup/pingpair_dyn
          #   - examples_backup/pingpair_irq
          #   - examples_backup/pingpair_irq_simple
          #   - examples_backup/pingpair_multi_dyn
          #   - examples_backup/pingpair_sleepy
          #   - examples_backup/rf24_ATTiny/rf24ping85
          #   - examples_backup/scanner
          #   - examples_backup/starping
          #   - examples_backup/Transfer
          #   - examples_backup/TransferTimeouts
          #   - examples_backup/Usage/led_remote
          #   - examples_backup/Usage/nordic_fob
          fqbn: ${{ matrix.fqbn }}
  attiny:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        fqbn:
          - attinyCore:avr:attinyx4
          - attinyCore:avr:attinyx4opti
          - attinyCore:avr:attinyx4micr
          - attinyCore:avr:attinyx5
          - attinyCore:avr:attinyx5micr
          - attinyCore:avr:attinyx8
          - attinyCore:avr:attinyx8opti
          - attinyCore:avr:attinyx8micr
          - attinyCore:avr:attinyx7
          - attinyCore:avr:attinyx7opti
          - attinyCore:avr:attinyx7micr
          - attinyCore:avr:attinyx61
          - attinyCore:avr:attinyx61opti
          - attinyCore:avr:attinyx41
          - attinyCore:avr:attinyx41opti
          - attinyCore:avr:attinyx41micr
          - attinyCore:avr:attiny43
          - attinyCore:avr:attiny828
          - attinyCore:avr:attiny828opti
          - attinyCore:avr:attiny1634
          - attinyCore:avr:attiny1634opti
          - attinyCore:avr:attinyx313

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile examples
        uses: arduino/compile-sketches@main
        with:
          name: ATTinyCore:avr
          source-url: https://github.com/SpenceKonde/ATTinyCore/archive/1.4.1.zip
          sketch-paths: |
            - examples/rf24_ATTiny
          # - examples/rf24_ATTiny/rf24ping85
          fqbn: ${{ matrix.fqbn }}