name: Linux build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        config-options:
          - "--soc=BCM2835 --driver=RPi"
          - "--soc=BCM2836 --driver=RPi"
          - "--soc=BCM2835 --driver=wiringPi --extra-cflags=-I/usr/local/include"
          - "--driver=SPIDEV"

    steps:
      - uses: actions/checkout@v1
      - name: provide toolchain
        run: |
          sudo apt-get update
          sudo apt-get install binutils-arm-linux-gnueabi gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
          arm-linux-gnueabihf-gcc -v
          arm-linux-gnueabihf-g++ -v
      - name: provide WiringPi
        if: ${{ matrix.config-options == '--soc=BCM2835 --driver=wiringPi --extra-cflags=-I/usr/local/include' }}
        run: |
          git clone https://github.com/CoRfr/WiringPi
          cd WiringPi/wiringPi
          CC="arm-linux-gnueabihf-gcc -marm -mtune=arm1176jzf-s -mfpu=vfp -mfloat-abi=hard" V=1 make -j5
          sudo make install
      - name: library configure
        run: ./configure ${{ matrix.config-options }}
      - name: library make
        run: make
      - name: library make install
        run: sudo make install
      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x86'
      - name: Install boost.python, RPi.GPIO, pylint
        run: |
          sudo apt-get install python3-dev libboost-python-dev python3-setuptools
          pip3 install RPi.GPIO pylint
      - name: build Python wrapper
        run: |
          sudo ln -s $(ls /usr/lib/arm-linux-gnueabihf/libboost_python3-py3*.so | tail -1) /usr/lib/arm-linux-gnueabihf/libboost_python3.so
          cd pyRF24
          python3 setup.py build
          python3 setup.py install
      - name: make linux examples
        # compiling examples for wiringPi is broken see nRF24#669 issue
        if: ${{ matrix.config-options != '--soc=BCM2835 --driver=wiringPi --extra-cflags=-I/usr/local/include' }}
        run: |
          cd examples_linux
          make
          file ./gettingstarted
      - name: check python examples
        run: |
          cd examples_linux
          pylint *.py --disable=invalid-name,no-name-in-module,no-member,duplicate-code
        # invalid-name,no-name-in-module,no-member are errors related to C++ wrapped into a python package; Applies to RF24 & RPi.GPIO packages
        # duplicate-code error gets flagged because some examples use similar code snippets
